[package]
name = "jvc_topic_scrapping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
scraper = "0.13.0"
reqwest = "0.11.11"
